driver: implement clGetDeviceInfo
sudo-team-company/red-o-lator pull request #4
Opened 2021-05-02 18:36 UTC by NewUserKK

* считывание параметров девайса с текстового конфига (путь пока захардкожен)

```
/usr/bin/clinfo --raw

#PLATFORMS                                        1
  CL_PLATFORM_NAME                                red-o-lator
  CL_PLATFORM_VENDOR                              sudo-team-company
  CL_PLATFORM_VERSION                             OpenCL 1.2 red-o-lator
  CL_PLATFORM_PROFILE                             FULL_PROFILE
  CL_PLATFORM_EXTENSIONS                          cl_khr_icd
  CL_PLATFORM_ICD_SUFFIX_KHR                      red-o-lator

[red-o-lator/*]   CL_PLATFORM_NAME                                red-o-lator
[red-o-lator/*] #DEVICES                                          1
[red-o-lator/0]   CL_DEVICE_NAME                                  Radeon RX 550 Series
[red-o-lator/0]   CL_DEVICE_VENDOR                                AMD
[red-o-lator/0]   CL_DEVICE_VENDOR_ID                             0x0
[red-o-lator/0]   CL_DEVICE_VERSION                               OpenCL 1.1 red-o-lator 1.0.0
[red-o-lator/0]   CL_DRIVER_VERSION                               1.0.0
[red-o-lator/0]   CL_DEVICE_OPENCL_C_VERSION                      OpenCL C 1.1
[red-o-lator/0]   CL_DEVICE_TYPE                                  CL_DEVICE_TYPE_GPU
[red-o-lator/0]   CL_DEVICE_PROFILE                               FULL_PROFILE
[red-o-lator/0]   CL_DEVICE_AVAILABLE                             CL_TRUE
[red-o-lator/0]   CL_DEVICE_COMPILER_AVAILABLE                    CL_TRUE
[red-o-lator/0]   CL_DEVICE_MAX_COMPUTE_UNITS                     8
[red-o-lator/0]   CL_DEVICE_MAX_CLOCK_FREQUENCY                   1206
[red-o-lator/0]   CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS              3
[red-o-lator/0]   CL_DEVICE_MAX_WORK_ITEM_SIZES                   <device_info_szptr_sep:1140: get %s : error -30>
[red-o-lator/0]   CL_DEVICE_MAX_WORK_GROUP_SIZE                   256
[red-o-lator/0]   CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE    <getWGsizes:673: create program : error -34>
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR           16
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR              16
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT          8
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT             8
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT            4
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_INT               4
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG           2
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG              2
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF           2
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF              2
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT          8
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT             8
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE         4
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE            4
Parameter 4147 was not found in config
[red-o-lator/0]   CL_DEVICE_HALF_FP_CONFIG                        
[red-o-lator/0]   CL_DEVICE_SINGLE_FP_CONFIG                      CL_FP_DENORM | CL_FP_INF_NAN
[red-o-lator/0]   CL_DEVICE_DOUBLE_FP_CONFIG                      
[red-o-lator/0]   CL_DEVICE_ADDRESS_BITS                          64
[red-o-lator/0]   CL_DEVICE_ENDIAN_LITTLE                         CL_TRUE
[red-o-lator/0]   CL_DEVICE_GLOBAL_MEM_SIZE                       0
[red-o-lator/0]   CL_DEVICE_ERROR_CORRECTION_SUPPORT              CL_FALSE
[red-o-lator/0]   CL_DEVICE_MAX_MEM_ALLOC_SIZE                    1901437747
[red-o-lator/0]   CL_DEVICE_HOST_UNIFIED_MEMORY                   CL_FALSE
Parameter 4122 was not found in config
[red-o-lator/0]   CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE              0
[red-o-lator/0]   CL_DEVICE_MEM_BASE_ADDR_ALIGN                   32768
[red-o-lator/0]   CL_DEVICE_GLOBAL_MEM_CACHE_TYPE                 CL_NONE
[red-o-lator/0]   CL_DEVICE_IMAGE_SUPPORT                         CL_FALSE
[red-o-lator/0]   CL_DEVICE_LOCAL_MEM_TYPE                        CL_LOCAL
[red-o-lator/0]   CL_DEVICE_LOCAL_MEM_SIZE                        0
[red-o-lator/0]   CL_DEVICE_MAX_CONSTANT_ARGS                     0
[red-o-lator/0]   CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE              0
[red-o-lator/0]   CL_DEVICE_MAX_PARAMETER_SIZE                    1024
[red-o-lator/0]   CL_DEVICE_QUEUE_PROPERTIES                      CL_QUEUE_PROFILING_ENABLE
[red-o-lator/0]   CL_DEVICE_PROFILING_TIMER_RESOLUTION            1
[red-o-lator/0]   CL_DEVICE_EXECUTION_CAPABILITIES                CL_EXEC_KERNEL
[red-o-lator/0]   CL_DEVICE_EXTENSIONS                            cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64 cl_khr_fp16

[OCLICD/*]   CL_ICDL_NAME                                    OpenCL ICD Loader
[OCLICD/*]   CL_ICDL_VENDOR                                  OCL Icd free software
[OCLICD/*]   CL_ICDL_VERSION                                 2.2.11
[OCLICD/*]   CL_ICDL_OCL_VERSION                             OpenCL 2.1
Unimplemented OpenCL API call: clCreateContext
```

2021-05-05 19:31 UTC, lukinma requested changes
В целом нормально, но надо поймать все исключения и добавить недостающие значения в конфиг (конфиг для RX550 2GB я прислал в дискорде). Ну и там ещё комменты по мелочи.

2021-05-05 19:31 UTC, lukinma commented on driver/resources/custom.ini
> +CL_DEVICE_GLOBAL_MEM_SIZE = 0
CL_DEVICE_GLOBAL_MEM_SIZE  2GiB либо 4GiB, нужны оба варианта.

2021-05-05 19:31 UTC, lukinma commented on driver/resources/custom.ini
> +CL_DEVICE_LOCAL_MEM_SIZE = 0
Local memory size:                             32768

2021-05-05 19:31 UTC, lukinma commented on driver/resources/rx-550.ini
> +CL_DEVICE_LOCAL_MEM_SIZE = 0
Local memory size:                             32768

2021-05-05 19:31 UTC, lukinma commented on driver/src/common/common.hpp
> +static std::pair<std::string, std::string> splitTwo(const std::string& line,
А почему другие функции в snake_case, а эта в camelCase?

2021-05-05 19:31 UTC, lukinma commented on driver/src/runtime/runtime-device.cpp
> +        kDeviceConfigurationParser.load(deviceConfigurationFile);
похоже, что мы не ловим exception, который летит из `splitTwo`.

2021-05-05 19:31 UTC, lukinma commented on driver/src/runtime/runtime-device.cpp
> +            "/home/newuserkk/Projects/ITMO/thesis/red-o-lator/driver/resources/"
Это будет работать только на вашем компе.

2021-05-05 19:31 UTC, lukinma commented on driver/src/runtime/device/DeviceConfigurationParser.cpp
> +    if (value == "CL_DEVICE_PARTITION_EQUALLY") {
Здесь и в других местах при сравнении с константой лучше писать  `"CL_DEVICE_PARTITION_EQUALLY" == value` для того, чтобы компилятор автоматически проверял опечатку = вместо ==.

2021-05-05 19:31 UTC, lukinma commented on driver/src/runtime/device/DeviceConfigurationParser.cpp
> +            parseParameter(trim(parameterName), trim(parameterValue));
Не нашёл, где обрабатывается исключение из функции `parseNumber`

2021-05-06 09:03 UTC, NewUserKK commented on driver/src/common/common.hpp
> +static std::pair<std::string, std::string> splitTwo(const std::string& line,
потому что trim* цинично скопировал с SO и забыл переименовать :)

2021-05-06 09:05 UTC, NewUserKK commented on driver/src/runtime/runtime-device.cpp
> +            "/home/newuserkk/Projects/ITMO/thesis/red-o-lator/driver/resources/"
это временная штука, да
потом здесь будет получение пути из эмулятора

2021-05-06 09:14 UTC, NewUserKK commented on driver/src/runtime/device/DeviceConfigurationParser.cpp
> +            parseParameter(trim(parameterName), trim(parameterValue));
при неправильном конфиге я решил, что будет лучше сразу упасть, чтобы пользователь его поправил

2021-05-06 09:19 UTC, NewUserKK commented on driver/src/runtime/device/DeviceConfigurationParser.cpp
> +    if (value == "CL_DEVICE_PARTITION_EQUALLY") {
тут у нас value это const&, так что будет ругаться и так
но учту в будущих местах

2021-05-08 12:33 UTC, NewUserKK commented
```
/usr/bin/clinfo --raw
#PLATFORMS                                        1
  CL_PLATFORM_NAME                                red-o-lator
  CL_PLATFORM_VENDOR                              sudo-team-company
  CL_PLATFORM_VERSION                             OpenCL 1.2 red-o-lator
  CL_PLATFORM_PROFILE                             FULL_PROFILE
  CL_PLATFORM_EXTENSIONS                          cl_khr_icd
  CL_PLATFORM_ICD_SUFFIX_KHR                      red-o-lator

[red-o-lator/*]   CL_PLATFORM_NAME                                red-o-lator
[red-o-lator/*] #DEVICES                                          1
Unknown parameter: CL_DEVICE_BOARD_NAME_AMD
Unknown parameter: CL_DEVICE_PCIE_ID_AMD
Unknown parameter: CL_DEVICE_TOPOLOGY_AMD
Unknown parameter: CL_DEVICE_SIMD_PER_COMPUTE_UNIT_AMD
Unknown parameter: CL_DEVICE_SIMD_WIDTH_AMD
Unknown parameter: CL_DEVICE_SIMD_INSTRUCTION_WIDTH_AMD
Unknown parameter: CL_DEVICE_GFXIP_MAJOR_AMD
Unknown parameter: CL_DEVICE_GFXIP_MINOR_AMD
Unknown parameter: CL_DEVICE_PREFERRED_WORK_GROUP_SIZE_AMD
Unknown parameter: CL_DEVICE_MAX_WORK_GROUP_SIZE_AMD
Unknown parameter: CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE
Unknown parameter: CL_DEVICE_WAVEFRONT_WIDTH_AMD
Unknown parameter: CL_DEVICE_HALF_FP_CONFIG
Unknown parameter: CL_DEVICE_GLOBAL_FREE_MEMORY_AMD
Unknown parameter: CL_DEVICE_GLOBAL_MEM_CHANNELS_AMD
Unknown parameter: CL_DEVICE_GLOBAL_MEM_CHANNEL_BANKS_AMD
Unknown parameter: CL_DEVICE_GLOBAL_MEM_CHANNEL_BANK_WIDTH_AMD
Unknown parameter: CL_DEVICE_SVM_CAPABILITIES
Unknown parameter: CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE
Unknown parameter: CL_DEVICE_PREFERRED_PLATFORM_ATOMIC_ALIGNMENT
Unknown parameter: CL_DEVICE_PREFERRED_GLOBAL_ATOMIC_ALIGNMENT
Unknown parameter: CL_DEVICE_PREFERRED_LOCAL_ATOMIC_ALIGNMENT
Unknown parameter: CL_DEVICE_MAX_GLOBAL_VARIABLE_SIZE
Unknown parameter: CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE
Unknown parameter: CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT
Unknown parameter: CL_DEVICE_IMAGE_PITCH_ALIGNMENT
Unknown parameter: CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS
Unknown parameter: CL_DEVICE_MAX_PIPE_ARGS
Unknown parameter: CL_DEVICE_PIPE_MAX_ACTIVE_RESERVATIONS
Unknown parameter: CL_DEVICE_PIPE_MAX_PACKET_SIZE
Unknown parameter: CL_DEVICE_LOCAL_MEM_SIZE_PER_COMPUTE_UNIT_AMD
Unknown parameter: CL_DEVICE_LOCAL_MEM_BANKS_AMD
Unknown parameter: CL_DEVICE_PREFERRED_CONSTANT_BUFFER_SIZE_AMD
Unknown parameter: CL_DEVICE_QUEUE_ON_HOST_PROPERTIES
Unknown parameter: CL_DEVICE_QUEUE_ON_DEVICE_PROPERTIES
Unknown parameter: CL_DEVICE_QUEUE_ON_DEVICE_PREFERRED_SIZE
Unknown parameter: CL_DEVICE_QUEUE_ON_DEVICE_MAX_SIZE
Unknown parameter: CL_DEVICE_MAX_ON_DEVICE_QUEUES
Unknown parameter: CL_DEVICE_MAX_ON_DEVICE_EVENTS
Unknown parameter: CL_DEVICE_PROFILING_TIMER_OFFSET_AMD
Unknown parameter: CL_DEVICE_THREAD_TRACE_SUPPORTED_AMD
Unknown parameter: CL_DEVICE_AVAILABLE_ASYNC_QUEUES_AMD
Unknown parameter: CL_DEVICE_MAX_REAL_TIME_COMPUTE_QUEUES_AMD
Unknown parameter: CL_DEVICE_MAX_REAL_TIME_COMPUTE_UNITS_AMD
Unknown parameter: CL_DEVICE_SPIR_VERSIONS
[red-o-lator/0]   CL_DEVICE_NAME                                  Ellesmere
[red-o-lator/0]   CL_DEVICE_VENDOR                                Advanced Micro Devices, Inc.
[red-o-lator/0]   CL_DEVICE_VENDOR_ID                             0x0
[red-o-lator/0]   CL_DEVICE_VERSION                               OpenCL 1.2 AMD (0.1)
[red-o-lator/0]   CL_DRIVER_VERSION                               0.1
[red-o-lator/0]   CL_DEVICE_OPENCL_C_VERSION                      OpenCL 1.2
[red-o-lator/0]   CL_DEVICE_TYPE                                  CL_DEVICE_TYPE_GPU
[red-o-lator/0]   CL_DEVICE_PROFILE                               FULL_PROFILE
[red-o-lator/0]   CL_DEVICE_AVAILABLE                             CL_TRUE
[red-o-lator/0]   CL_DEVICE_COMPILER_AVAILABLE                    CL_TRUE
[red-o-lator/0]   CL_DEVICE_LINKER_AVAILABLE                      CL_TRUE
[red-o-lator/0]   CL_DEVICE_MAX_COMPUTE_UNITS                     32
[red-o-lator/0]   CL_DEVICE_MAX_CLOCK_FREQUENCY                   1256
[red-o-lator/0]   CL_DEVICE_PARTITION_MAX_SUB_DEVICES             32
[red-o-lator/0]   CL_DEVICE_PARTITION_PROPERTIES                  <device_info_partition_types:1466: get %s : error -30>
[red-o-lator/0]   CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS              3
[red-o-lator/0]   CL_DEVICE_MAX_WORK_ITEM_SIZES                   <device_info_szptr_sep:1140: get %s : error -30>
[red-o-lator/0]   CL_DEVICE_MAX_WORK_GROUP_SIZE                   256
[red-o-lator/0]   CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE    <getWGsizes:673: create program : error -34>
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR           4
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_CHAR              4
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT          2
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_SHORT             2
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT            1
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_INT               1
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG           1
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_LONG              1
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_HALF           1
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_HALF              1
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT          1
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_FLOAT             1
[red-o-lator/0]   CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE         1
[red-o-lator/0]   CL_DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE            1
[red-o-lator/0]   CL_DEVICE_SINGLE_FP_CONFIG                      CL_FP_INF_NAN | CL_FP_ROUND_TO_NEAREST | CL_FP_ROUND_TO_ZERO | CL_FP_ROUND_TO_INF | CL_FP_FMA | CL_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT
[red-o-lator/0]   CL_DEVICE_ADDRESS_BITS                          64
[red-o-lator/0]   CL_DEVICE_ENDIAN_LITTLE                         CL_TRUE
[red-o-lator/0]   CL_DEVICE_GLOBAL_MEM_SIZE                       4294967296
[red-o-lator/0]   CL_DEVICE_ERROR_CORRECTION_SUPPORT              CL_FALSE
[red-o-lator/0]   CL_DEVICE_MAX_MEM_ALLOC_SIZE                    3422552064
[red-o-lator/0]   CL_DEVICE_HOST_UNIFIED_MEMORY                   CL_FALSE
Parameter 4122 was not found in config
[red-o-lator/0]   CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE              0
[red-o-lator/0]   CL_DEVICE_MEM_BASE_ADDR_ALIGN                   2048
[red-o-lator/0]   CL_DEVICE_GLOBAL_MEM_CACHE_TYPE                 CL_READ_WRITE_CACHE
[red-o-lator/0]   CL_DEVICE_GLOBAL_MEM_CACHE_SIZE                 16384
[red-o-lator/0]   CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE             64
[red-o-lator/0]   CL_DEVICE_IMAGE_SUPPORT                         CL_TRUE
[red-o-lator/0]   CL_DEVICE_MAX_SAMPLERS                          16
[red-o-lator/0]   CL_DEVICE_IMAGE_MAX_BUFFER_SIZE                 134217728
[red-o-lator/0]   CL_DEVICE_IMAGE_MAX_ARRAY_SIZE                  2048
[red-o-lator/0]   CL_DEVICE_IMAGE2D_MAX_HEIGHT                    16384
[red-o-lator/0]   CL_DEVICE_IMAGE2D_MAX_WIDTH                     16384
[red-o-lator/0]   CL_DEVICE_IMAGE3D_MAX_HEIGHT                    2048
[red-o-lator/0]   CL_DEVICE_IMAGE3D_MAX_WIDTH                     2048
[red-o-lator/0]   CL_DEVICE_IMAGE3D_MAX_DEPTH                     2048
[red-o-lator/0]   CL_DEVICE_MAX_READ_IMAGE_ARGS                   128
[red-o-lator/0]   CL_DEVICE_MAX_WRITE_IMAGE_ARGS                  64
[red-o-lator/0]   CL_DEVICE_LOCAL_MEM_TYPE                        CL_LOCAL
[red-o-lator/0]   CL_DEVICE_LOCAL_MEM_SIZE                        32768
[red-o-lator/0]   CL_DEVICE_MAX_CONSTANT_ARGS                     8
[red-o-lator/0]   CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE              3422552064
[red-o-lator/0]   CL_DEVICE_MAX_PARAMETER_SIZE                    1024
Parameter 4138 was not found in config
[red-o-lator/0]   CL_DEVICE_QUEUE_PROPERTIES                      
[red-o-lator/0]   CL_DEVICE_PREFERRED_INTEROP_USER_SYNC           CL_TRUE
[red-o-lator/0]   CL_DEVICE_PROFILING_TIMER_RESOLUTION            1
[red [...]

2021-05-08 12:37 UTC, NewUserKK commented on driver/resources/custom.ini
> +CL_DEVICE_GLOBAL_MEM_SIZE = 0
здесь и далее: перешёл на конфиг 570 из clinfo

2021-05-13 09:00 UTC, lukinma approved these changes

2021-05-13 09:01 UTC, merged