driver: implement basic opencl api up to clCreateKernel
sudo-team-company/red-o-lator pull request #6
Opened 2021-05-13 18:36 UTC by NewUserKK

Implemented:
- context API
- in-order command queue
- create, read, write buffers
- program API

Current ethminer output:
```
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer --simulation 20

ethminer 0.19.0-17+commit.ce52c740.dirty
Build: linux/debug/gnu

[red-o-lator driver] --- Ignoring parameter CL_DRIVER_VERSION
[red-o-lator driver] --- Ignoring parameter CL_DEVICE_OPENCL_C_VERSION
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PCIE_ID_AMD
[red-o-lator driver] --- Ignoring parameter CL_DEVICE_AVAILABLE
[red-o-lator driver] --- Ignoring parameter CL_DEVICE_COMPILER_AVAILABLE
[red-o-lator driver] --- Ignoring parameter CL_DEVICE_LINKER_AVAILABLE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_GFXIP_MAJOR_AMD
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_GFXIP_MINOR_AMD
[red-o-lator driver] --- Ignoring parameter CL_DEVICE_PARTITION_MAX_SUB_DEVICES
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PREFERRED_WORK_GROUP_SIZE_AMD
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_WORK_GROUP_SIZE_AMD
[red-o-lator driver] --- Unknown parameter: CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_HALF_FP_CONFIG
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_SVM_CAPABILITIES
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PREFERRED_PLATFORM_ATOMIC_ALIGNMENT
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PREFERRED_GLOBAL_ATOMIC_ALIGNMENT
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PREFERRED_LOCAL_ATOMIC_ALIGNMENT
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_GLOBAL_VARIABLE_SIZE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_IMAGE_PITCH_ALIGNMENT
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_READ_WRITE_IMAGE_ARGS
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_PIPE_ARGS
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PIPE_MAX_ACTIVE_RESERVATIONS
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PIPE_MAX_PACKET_SIZE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_PREFERRED_CONSTANT_BUFFER_SIZE_AMD
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_QUEUE_ON_HOST_PROPERTIES
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_QUEUE_ON_DEVICE_PROPERTIES
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_QUEUE_ON_DEVICE_PREFERRED_SIZE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_QUEUE_ON_DEVICE_MAX_SIZE
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_ON_DEVICE_QUEUES
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_ON_DEVICE_EVENTS
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_THREAD_TRACE_SUPPORTED_AMD
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_AVAILABLE_ASYNC_QUEUES_AMD
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_REAL_TIME_COMPUTE_QUEUES_AMD
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_MAX_REAL_TIME_COMPUTE_UNITS_AMD
[red-o-lator driver] --- Unknown parameter: CL_DEVICE_SPIR_VERSIONS
 i 21:28:45 ethminer Selected pool localhost:0
 i 21:28:45 ethminer Established connection to localhost:0
 i 21:28:45 ethminer Spinning up miners...
cl 21:28:45 cl-0     Using Device : 00:00.0 Ellesmere OpenCL 1.2 AMD (0.1) Memory : 4.00 GB (4294967296 B)
 i 21:28:45 cl-0     Adjusting CL work multiplier for 32 CUs. Adjusted work multiplier: 58,255
 i 21:28:45 sim      Epoch : 0 Difficulty : 4.29 Gh
 i 21:28:45 sim      Job: 4357656c… block 20 localhost:0
cl 21:28:45 cl-0     Generating split DAG + Light (total): 1024.00 MB
cl 21:28:45 cl-0     OpenCL kernel
cl 21:28:45 cl-0     Loading binary kernel /home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/kernels/ethash_ellesmere_lws128_exit.bin
cl 21:28:45 cl-0     Build info success: Binary build is not supported, assuming binary was already built for AMD platform.
cl 21:28:45 cl-0     Creating DAG buffer, size: 1024.00 MB, free: 3.00 GB
cl 21:28:46 cl-0     Creating light cache buffer, size: 16.00 MB
cl 21:28:46 cl-0     Loading kernels
Unimplemented OpenCL API call: clCreateKernel
Unimplemented OpenCL API call: clCreateKernel
 X 21:28:46 cl-0     Creating DAG buffer failed: clCreateKernel: Unknown CL error encountered (32594)
SIGSEGV encountered ...
stack trace:
backtrace() returned 13 addresses
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x93e82) [0x5638643c3e82]
/lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f5275fc0040]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x40f028) [0x56386473f028]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x4108f1) [0x5638647408f1]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x1d09da) [0x5638645009da]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x1d19b5) [0x5638645019b5]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x1d11b9) [0x5638645011b9]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x1d1e4a) [0x563864501e4a]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x1d1e06) [0x563864501e06]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x1d1dd6) [0x563864501dd6]
/home/newuserkk/Projects/ITMO/thesis/ethminer/cmake-build-debug/ethminer/ethminer(+0x49adcf) [0x5638647cadcf]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f527692f6db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f52760a271f]
```

2021-05-13 23:37 UTC, lukinma requested changes

2021-05-13 23:37 UTC, lukinma commented on debugger/CMakeLists.txt
> +target_link_libraries(debugger red-o-lator-common)
no new line at the end of the file

2021-05-13 23:37 UTC, lukinma commented on driver/src/runtime/runtime-commons.h
> +#define GET_PARAM_INFO(fn)                                                    \
Такие макросы опасны. Слишком многое может пойти не так. Если такой многострочный макрос очень нужен, то следует его хотя бы обернуть в безопасную обёртку, например, `do {/*тело макроса*/} while (false)`.

А вообще лучше такой макрос несложно переписать в функцию.

2021-05-14 22:34 UTC, lukinma requested changes

2021-05-15 17:33 UTC, NewUserKK commented
следующий ПР: https://github.com/NewUserKK/red-o-lator/pull/5
(сделал в форк в ветку, чтобы не накидывать новые коммиты сюда)

2021-05-16 21:51 UTC, lukinma requested changes
Осталось пофиксить сборку CI/CD.

2021-05-17 10:39 UTC, lukinma approved these changes

2021-05-17 10:39 UTC, merged